### ISSUE TITLE
Checklist for Investigation Class

### ISSUE THREAD

**Issue by schristley** [airr-knowledge/issues#25]
- [x] Is the class an entity or a process? Is it an information entity about a material entity/process, or a pure information entity/process?
- [x] Specify the ontology URI for class. Is there a hierarchy of ontology terms that are relevant?
- [x] Define the slots for the class. Every slot should have an URI either to an ontology term or schema.org term for its semantics. Is there a hierarchy of terms that are relevant for its semantics?
- [x] Define the attributes of each slot. Identifier? Required? Data type? Controlled vocabulary or ontology for the values?
- [x] Define the direct relations to other objects. What is the cardinality of the relation? Is there an ontology URI for the relation?
- [x] If the class is a process, there should be slots for the inputs/outputs of the process. They may be directly defined in the class or are relations.
- [x] Should any slots be potential made into a class? Is the class a composite of other classes?

- [x] Review and approval by each group (ADC, IEDB, IRAD, OGRDB)

**Comment by schristley** [comment]
> * [ ]  Is the class an entity or a process? Is it an information entity about a material entity/process, or a pure information entity/process?

Information entity.

**Comment by bpeters42** [comment]
An investigation in OBI is a process. It endures in time, has process parts (like performing assays or analysis) and has inputs and outputs (like conclusions).

**Comment by schristley** [comment]
> * [ ]  Specify the ontology URI for class. Is there a hierarchy of ontology terms that are relevant?

OBI:0000066 # investigation

**Comment by schristley** [comment]
> * [ ]  Define the slots for the class. Every slot should have an URI either to an ontology term or schema.org term for its semantics. Is there a hierarchy of terms that are relevant for its semantics?

Has a plan (study design) for how the investigation will be performed. Has participants, has assays, produces documents, and produces conclusions.

The investigation should also point to how the plan (study design) was executed? The miro diagram has this indirectly in that study events (part of the study design) are linked to life course events. I'm thinking there should be an `study design execution class` as an overall umbrella, with life course events being a part of it.

**Comment by schristley** [comment]
> * [ ]  If the class is a process, there should be slots for the inputs/outputs of the process. They may be directly defined in the class or are relations.

The outputs are the `documents` and the `conclusions`. The input is the `study_design`

**Comment by schristley** [comment]
initial design in v0.2
