### ISSUE TITLE
Checklist for Adaptive Immune Receptor Class

### ISSUE THREAD

**Issue by KevinABurns137** [airr-knowledge/issues#26]
- [x] Is the class an entity or a process? Is it an information entity about a material entity/process, or a pure information entity/process?
- [x] Specify the ontology URI for class. Is there a hierarchy of ontology terms that are relevant?
- [x] Define the slots for the class. Every slot should have an URI either to an ontology term or schema.org term for its semantics. Is there a hierarchy of terms that are relevant for its semantics?
- [x] Define the attributes of each slot. Identifier? Required? Data type? Controlled vocabulary or ontology for the values?
- [x] Define the direct relations to other objects. What is the cardinality of the relation? Is there an ontology URI for the relation?
- [x] If the class is a process, there should be slots for the inputs/outputs of the process. They may be directly defined in the class or are relations.
- [x] Should any slots be potential made into a class? Is the class a composite of other classes?

- [x] Review and approval by each group (ADC, IEDB, IRAD, OGRDB)

**Comment by schristley** [comment]
> * [ ]  Is the class an entity or a process? Is it an information entity about a material entity/process, or a pure information entity/process?

Material entity.

**Comment by schristley** [comment]
An [initial schema](https://github.com/airr-knowledge/ak-schema/pull/8) has been defined.

**Comment by schristley** [comment]
Initial data integration from ADC rearrangements and from IEDB receptors suggests that the initial schema is sufficient for this milestone.
